export interface Affiliates {
    codigoPersona?: string,
    cuspp?: string,
    identificacionTipo?: string,
    identificacionNumero?: string,
    apellidoPaterno?: string,
    apellidoMaterno?: string,
    nombrePrimero?: string,
    nombreSegundo?: string,
    indicadorRetiro?: string,
    motivoRetiro?: string,
    fechaNacimiento?: string,
    sexo?: string,
    direccionAvenida?: string,
    direccionNumero?: string,
    direccionUrbanizacion?: string,
    departamentoDescripcion?: string,
    provinciaDescripcion?: string,
    distritoDescripcion?: string,
    direccionReferencia?: string,
    telefonoResidencia?: string,
    telefonoOficina?: string,
    celular?: string,
    emailPrincipal?: string,
    emailSecundario?: string
}